version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "/"
      - "/tests/coordination/base"
      - "/tests/storage/block/balancer"
      - "/tests/storage/block/base"
      - "/tests/storage/block/blockmanagement"
      - "/tests/storage/block/datanode"
      - "/tests/storage/block/dfs-base"
      - "/tests/storage/block/fs-base"
      - "/tests/storage/block/misc"
      - "/tests/storage/block/namenode"
    schedule:
      interval: "daily"
